services:
  frontend:
    image: ghcr.io/sewaustav/casego-frontend:latest
    build:
      context: .
    container_name: casego_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - /etc/letsencrypt:/etc/letsencrypt:ro
     - /opt/3x-ui/subscription/sub.json:/usr/share/nginx/html/sub.json:ro
    restart: unless-stopped
