services:
  frontend:
    image: ghcr.io/sewaustav/casego-frontend:latest
    build:
      context: .
      args:
        AUTH_URL: http://${SERVER_IP}:8000/api/v1/auth
        PROFILE_URL: http://${SERVER_IP}:8080/profile/api/v1
        CASE_GO_URL: http://${SERVER_IP}:8081/api/v1/case_go
        CASE_PROFILE_URL: http://${SERVER_IP}:8082/api/v1/case_go
    container_name: casego_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
