services:
  frontend:
    image: ghcr.io/sewaustav/casego-frontend:latest
    build:
      context: .
    container_name: casego_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - /etc/letsencrypt:/etc/letsencrypt:ro
     - /opt/3x-ui/subscription:/usr/share/nginx/html/sub:ro
    restart: unless-stopped
    networks:
      - default
      - backend

networks:
  backend:
    external: true
    name: backend_app-network
