server {
    listen 80;
    server_name casego.ddns.net;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name casego.ddns.net;

    ssl_certificate /etc/letsencrypt/live/casego.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/casego.ddns.net/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript
               text/xml application/xml application/xml+rss text/javascript
               application/wasm;
}
